import {
  SupplierDTO,
  ProcurementRequest,
  SupplierOffer,
  Negotiation,
  PurchaseOrder,
  DocumentDTO,
  Shipment,
  RiskEventDTO,
  NotificationDTO,
  SupplierSourceDTO
} from '@/lib/types';

export const mockSources: SupplierSourceDTO[] = [
  {
    id: 'src-ondc',
    name: 'ONDC Network',
    code: 'ONDC',
    description: 'India digital commerce network with open discovery and Beckn protocol communication.',
    isOfficial: true,
    isConnected: true,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: true,
      canNegotiate: true,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: true,
      negotiation: true,
      ordering: true,
      tracking: false
    }
  },
  {
    id: 'src-direct',
    name: 'Direct Supplier API',
    code: 'DIRECT_API',
    description: 'Direct enterprise vendor webhook integration with instant pricing and tracking.',
    isOfficial: true,
    isConnected: true,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: true,
      canNegotiate: true,
      canCreateOrder: true,
      canTrackShipment: true,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: true,
      negotiation: true,
      ordering: true,
      tracking: true
    }
  },
  {
    id: 'src-mkt-x',
    name: 'Marketplace X',
    code: 'MARKETPLACE_X',
    description: 'Read-only commercial catalogue. Automated negotiation is explicitly unavailable.',
    isOfficial: true,
    isConnected: true,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: false,
      canNegotiate: false,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: false,
      negotiation: false,
      ordering: true,
      tracking: false
    }
  }
];

export const mockSuppliersDatabase: SupplierDTO[] = [
  {
    id: 'sahara',
    name: 'Sahara Workspace',
    sourceId: 'MARKETPLACE_X',
    sourceName: 'Marketplace X',
    sourceExternalId: 'mkt-sahara-01',
    product: 'Ergonomic task chair',
    price: 750,
    availability: 600,
    delivery: '5 days',
    deliveryDays: 5,
    reliability: 91,
    rating: 4.6,
    location: 'Bengaluru',
    source: 'Marketplace X',
    why: 'Strong fulfilment history across southern distribution hubs.',
    communication: false,
    ordersCompleted: 28,
    onTimeDeliveryRate: 90,
    averageResponseMins: 45,
    averageSavingsPct: 4.2,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: false,
      canNegotiate: false,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: false,
      negotiation: false,
      ordering: true,
      tracking: false
    },
    hasMessagingChannel: false,
    email: 'sales@saharaworkspace.in',
    phone: '+91-80-4122-8899'
  },
  {
    id: 'cobalt',
    name: 'Cobalt Office Systems',
    sourceId: 'ONDC',
    sourceName: 'ONDC Network',
    sourceExternalId: 'ondc-seller-cobalt-01',
    product: 'Ergonomic task chair',
    price: 740,
    availability: 500,
    delivery: '4 days',
    deliveryDays: 4,
    reliability: 98,
    rating: 4.9,
    location: 'Chennai',
    source: 'ONDC',
    why: 'Best overall match with lowest landed cost and fastest 4-day delivery.',
    communication: true,
    ordersCompleted: 42,
    onTimeDeliveryRate: 97,
    averageResponseMins: 18,
    averageSavingsPct: 6.8,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: true,
      canNegotiate: true,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: true,
      negotiation: true,
      ordering: true,
      tracking: false
    },
    hasMessagingChannel: true,
    email: 'orders@cobaltoffice.in',
    phone: '+91-44-2834-9100'
  },
  {
    id: 'ernest',
    name: 'Ernest Furnishings',
    sourceId: 'ONDC',
    sourceName: 'ONDC Network',
    sourceExternalId: 'ondc-seller-ernest-02',
    product: 'Ergonomic task chair',
    price: 735,
    availability: 800,
    delivery: '5 days',
    deliveryDays: 5,
    reliability: 93,
    rating: 4.7,
    location: 'Coimbatore',
    source: 'ONDC',
    why: 'Lowest unit price at ₹735/unit with strong catalog inventory.',
    communication: true,
    ordersCompleted: 35,
    onTimeDeliveryRate: 92,
    averageResponseMins: 24,
    averageSavingsPct: 5.5,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: true,
      canNegotiate: true,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: true,
      negotiation: true,
      ordering: true,
      tracking: false
    },
    hasMessagingChannel: true,
    email: 'b2b@ernestfurnishings.com',
    phone: '+91-422-265-4421'
  },
  {
    id: 'dwell',
    name: 'Dwell Business',
    sourceId: 'DIRECT_API',
    sourceName: 'Direct Supplier API',
    sourceExternalId: 'direct-dwell-01',
    product: 'Ergonomic task chair',
    price: 748,
    availability: 520,
    delivery: '6 days',
    deliveryDays: 6,
    reliability: 95,
    rating: 4.8,
    location: 'Chennai',
    source: 'Direct API',
    why: 'Direct enterprise vendor with premium quality certification and warranty.',
    communication: true,
    ordersCompleted: 19,
    onTimeDeliveryRate: 94,
    averageResponseMins: 15,
    averageSavingsPct: 5.1,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: true,
      canNegotiate: true,
      canCreateOrder: true,
      canTrackShipment: true,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: true,
      negotiation: true,
      ordering: true,
      tracking: true
    },
    hasMessagingChannel: true,
    email: 'procure@dwellbusiness.com',
    phone: '+91-44-4900-1122'
  },
  {
    id: 'aura',
    name: 'Aura Commercial',
    sourceId: 'MARKETPLACE_X',
    sourceName: 'Marketplace X',
    sourceExternalId: 'mkt-aura-02',
    product: 'Ergonomic task chair',
    price: 760,
    availability: 1000,
    delivery: '4 days',
    deliveryDays: 4,
    reliability: 89,
    rating: 4.4,
    location: 'Hyderabad',
    source: 'Marketplace X',
    why: 'High stock volume (1,000 units); automated messaging not supported.',
    communication: false,
    ordersCompleted: 14,
    onTimeDeliveryRate: 88,
    averageResponseMins: 50,
    averageSavingsPct: 3.5,
    capabilities: {
      canSearch: true,
      canGetProductDetails: true,
      canGetSellerDetails: true,
      canGetSellerContact: true,
      canGetPricing: true,
      canGetAvailability: true,
      canMessageSeller: false,
      canNegotiate: false,
      canCreateOrder: true,
      canTrackShipment: false,
      search: true,
      sellerDetails: true,
      pricing: true,
      availability: true,
      messaging: false,
      negotiation: false,
      ordering: true,
      tracking: false
    },
    hasMessagingChannel: false,
    email: 'b2b@auracommercial.com',
    phone: '+91-40-2344-7711'
  }
];

export const mockRequestsStore: ProcurementRequest[] = [
  {
    id: 'req-1827',
    businessId: 'biz_kinetiq_01',
    referenceNumber: 'REQ-2026-1827',
    title: 'Ergonomic office chairs',
    rawRequirement: 'I need 500 ergonomic office chairs under ₹750 per unit, delivered to Chennai within 5 days.',
    productCategory: 'Commercial Furniture',
    quantity: 500,
    budget: 375000,
    targetUnitPrice: 720,
    maxUnitPrice: 750,
    deliveryLocation: 'Chennai',
    deadline: '5 days',
    deliveryDeadline: '5 days',
    allowPartial: false,
    status: 'review',
    whyExplanation: 'Ranked from real supplier records returned by connected sources.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'req-2044',
    businessId: 'biz_kinetiq_01',
    referenceNumber: 'REQ-2026-2044',
    title: 'Warehouse heavy shelving',
    rawRequirement: 'Industrial racks and warehouse shelving for Bengaluru fulfillment center.',
    productCategory: 'Industrial Supplies',
    quantity: 50,
    budget: 112500,
    targetUnitPrice: 2200,
    maxUnitPrice: 2300,
    deliveryLocation: 'Bengaluru',
    deadline: '7 days',
    deliveryDeadline: '7 days',
    allowPartial: false,
    status: 'searching',
    whyExplanation: 'Active search across ONDC and connected supplier networks.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'req-1819',
    businessId: 'biz_kinetiq_01',
    referenceNumber: 'REQ-2026-1819',
    title: 'Industrial barcode labels',
    rawRequirement: '5,000 thermal industrial roll labels delivered to Chennai.',
    productCategory: 'Packaging',
    quantity: 5000,
    budget: 44800,
    targetUnitPrice: 8.5,
    maxUnitPrice: 9.0,
    deliveryLocation: 'Chennai',
    deadline: '3 days',
    deliveryDeadline: '3 days',
    allowPartial: false,
    status: 'approved',
    whyExplanation: 'PO issued and currently in transit.',
    createdAt: new Date().toISOString()
  }
];

export const mockNegotiationsStore: Negotiation[] = [
  {
    id: 'neg-cobalt',
    businessId: 'biz_kinetiq_01',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    requestId: 'req-1827',
    sessionCode: 'NEG-1089',
    status: 'ACCEPTED',
    targetPrice: 720,
    maxPrice: 750,
    quantity: 500,
    maxRounds: 3,
    currentRound: 3,
    freightRequired: true,
    channelResolved: 'ONDC_MESSAGING',
    channelStatus: 'AVAILABLE',
    finalOfferPrice: 740,
    savingsAmount: 20000,
    messages: [
      {
        id: 'msg-1',
        negotiationId: 'neg-cobalt',
        senderType: 'PROCURA_AI',
        senderName: 'Procura',
        content: 'Can you offer your best bulk price for 500 ergonomic office chairs?',
        provenance: 'Official ONDC messaging · 14:31 IST',
        createdAt: '2026-09-01T09:01:00Z'
      },
      {
        id: 'msg-2',
        negotiationId: 'neg-cobalt',
        senderType: 'SUPPLIER',
        senderName: 'Cobalt Office Systems',
        content: 'We can offer ₹750 per unit, with freight included.',
        provenance: 'Official ONDC messaging · 14:36 IST',
        createdAt: '2026-09-01T09:06:00Z'
      },
      {
        id: 'msg-3',
        negotiationId: 'neg-cobalt',
        senderType: 'PROCURA_AI',
        senderName: 'Procura',
        content: 'If we confirm all 500 units and payment is made promptly, can you do ₹740 including delivery?',
        provenance: 'Official ONDC messaging · 14:39 IST',
        createdAt: '2026-09-01T09:09:00Z'
      },
      {
        id: 'msg-4',
        negotiationId: 'neg-cobalt',
        senderType: 'SUPPLIER',
        senderName: 'Cobalt Office Systems',
        content: 'Confirmed: ₹740/unit, freight included, delivery in 4 days.',
        provenance: 'Official ONDC messaging · 14:42 IST',
        createdAt: '2026-09-01T09:12:00Z'
      }
    ],
    rounds: [
      {
        id: 'rnd-1',
        roundNumber: 1,
        buyerProposal: 'Bulk pricing inquiry for 500 chairs',
        sellerCounter: '₹750 with freight included',
        priceProposed: 720,
        priceCountered: 750,
        completedAt: '2026-09-01T09:06:00Z'
      },
      {
        id: 'rnd-2',
        roundNumber: 2,
        buyerProposal: 'Prompt payment trade-off for ₹740',
        sellerCounter: 'Confirmed: ₹740/unit',
        priceProposed: 740,
        priceCountered: 740,
        completedAt: '2026-09-01T09:12:00Z'
      }
    ],
    currentOffer: {
      id: 'off-cobalt-final',
      requestId: 'req-1827',
      supplierId: 'cobalt',
      supplierName: 'Cobalt Office Systems',
      negotiationId: 'neg-cobalt',
      roundNumber: 2,
      unitPrice: 740,
      quantity: 500,
      moq: 50,
      freight: 'included',
      deliveryDays: 4,
      paymentTerms: '30% advance, balance on delivery',
      warrantyTerms: '2 years warranty',
      source: 'ONDC',
      sourceProvenance: 'Official ONDC protocol negotiation record',
      verifiedAt: '14:42 IST',
      isBuyerApproved: false,
      isBestOffer: true,
      savingsVsInitial: 20000
    },
    createdAt: '2026-09-01T09:00:00Z'
  },
  {
    id: 'neg-ernest',
    businessId: 'biz_kinetiq_01',
    supplierId: 'ernest',
    supplierName: 'Ernest Furnishings',
    requestId: 'req-1827',
    sessionCode: 'NEG-1091',
    status: 'ACTIVE',
    targetPrice: 720,
    maxPrice: 750,
    quantity: 500,
    maxRounds: 3,
    currentRound: 1,
    freightRequired: true,
    channelResolved: 'ONDC_MESSAGING',
    channelStatus: 'AVAILABLE',
    finalOfferPrice: 735,
    savingsAmount: 22500,
    messages: [
      {
        id: 'msg-ernest-1',
        negotiationId: 'neg-ernest',
        senderType: 'PROCURA_AI',
        senderName: 'Procura',
        content: 'Requesting bulk discount for 500 units at ₹720 with delivery to Chennai.',
        provenance: 'Official ONDC messaging · 14:31 IST',
        createdAt: '2026-09-01T09:01:00Z'
      },
      {
        id: 'msg-ernest-2',
        negotiationId: 'neg-ernest',
        senderType: 'SUPPLIER',
        senderName: 'Ernest Furnishings',
        content: 'Our quotation is ₹735/unit + standard freight (approx ₹15/unit). Delivery in 5 days.',
        provenance: 'Official ONDC messaging · 14:38 IST',
        createdAt: '2026-09-01T09:08:00Z'
      }
    ],
    rounds: [
      {
        id: 'rnd-ernest-1',
        roundNumber: 1,
        buyerProposal: 'Requesting ₹720/unit',
        sellerCounter: '₹735/unit + freight extra',
        priceProposed: 720,
        priceCountered: 735,
        completedAt: '2026-09-01T09:08:00Z'
      }
    ],
    createdAt: '2026-09-01T09:00:00Z'
  },
  {
    id: 'neg-sahara',
    businessId: 'biz_kinetiq_01',
    supplierId: 'sahara',
    supplierName: 'Sahara Workspace',
    requestId: 'req-1827',
    sessionCode: 'NEG-1093',
    status: 'COMMUNICATION_UNAVAILABLE',
    targetPrice: 720,
    maxPrice: 750,
    quantity: 500,
    maxRounds: 3,
    currentRound: 1,
    channelResolved: 'NONE',
    channelStatus: 'COMMUNICATION_UNAVAILABLE',
    messages: [
      {
        id: 'msg-sahara-1',
        negotiationId: 'neg-sahara',
        senderType: 'SYSTEM',
        senderName: 'Procura Channel Router',
        content: 'Communication unavailable: This connected source (Marketplace X) does not permit automated supplier negotiation.',
        provenance: 'Provider capability check at 14:30 IST',
        createdAt: '2026-09-01T09:00:00Z'
      }
    ],
    createdAt: '2026-09-01T09:00:00Z'
  }
];

export const mockOffersDatabase: SupplierOffer[] = [
  {
    id: 'off-cobalt',
    requestId: 'req-1827',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    negotiationId: 'neg-cobalt',
    roundNumber: 2,
    unitPrice: 740,
    quantity: 500,
    moq: 50,
    freight: 'included',
    freightCost: 0,
    taxRate: 18.0,
    totalAmount: 436600,
    deliveryDays: 4,
    paymentTerms: '30% advance, balance on delivery',
    warrantyTerms: '2 years warranty',
    source: 'ONDC',
    sourceProvenance: 'Official ONDC protocol negotiation record',
    verifiedAt: '14:42 IST',
    isBuyerApproved: true,
    isBestOffer: true,
    savingsVsInitial: 20000
  },
  {
    id: 'off-ernest',
    requestId: 'req-1827',
    supplierId: 'ernest',
    supplierName: 'Ernest Furnishings',
    negotiationId: 'neg-ernest',
    roundNumber: 1,
    unitPrice: 735,
    quantity: 500,
    moq: 100,
    freight: 'extra',
    freightCost: 7500,
    taxRate: 18.0,
    totalAmount: 442500,
    deliveryDays: 5,
    paymentTerms: '50% advance',
    warrantyTerms: '1 year warranty',
    source: 'ONDC',
    sourceProvenance: 'Official ONDC protocol quotation record',
    verifiedAt: '14:38 IST',
    isBuyerApproved: false,
    isBestOffer: false,
    savingsVsInitial: 22500
  },
  {
    id: 'off-dwell',
    requestId: 'req-1827',
    supplierId: 'dwell',
    supplierName: 'Dwell Business',
    negotiationId: 'neg-dwell',
    roundNumber: 1,
    unitPrice: 748,
    quantity: 500,
    moq: 20,
    freight: 'included',
    freightCost: 0,
    taxRate: 18.0,
    totalAmount: 441320,
    deliveryDays: 6,
    paymentTerms: 'Net 30',
    warrantyTerms: '3 years warranty',
    source: 'Direct API',
    sourceProvenance: 'Direct vendor API webhook quote',
    verifiedAt: '14:35 IST',
    isBuyerApproved: false,
    isBestOffer: false,
    savingsVsInitial: 16000
  }
];

export const mockPurchaseOrdersStore: PurchaseOrder[] = [
  {
    id: 'po-1827',
    businessId: 'biz_kinetiq_01',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    requestId: 'req-1827',
    offerId: 'off-cobalt',
    poNumber: 'PO-1827',
    status: 'APPROVED',
    subtotal: 370000,
    taxAmount: 66600,
    freightAmount: 0,
    total: 370000,
    totalAmount: 436600,
    paymentTerms: '30% advance, 70% against delivery',
    deliveryTerms: 'Door delivery Chennai warehouse',
    deliveryAddress: 'Plot 42, Guindy Industrial Estate, Chennai 600032',
    expectedDelivery: '4 Sep 2026',
    approvedBy: 'Sadwik Kumar',
    approvedAt: '2026-09-01T09:15:00Z',
    items: [
      {
        id: 'item-1',
        itemName: 'Ergonomic office chairs',
        specifications: 'High-density mesh back, adjustable lumbar support, 2-year warranty',
        quantity: 500,
        unitPrice: 740,
        taxRate: 18.0,
        totalAmount: 370000
      }
    ],
    createdAt: '2026-08-28T10:00:00Z'
  },
  {
    id: 'po-1819',
    businessId: 'biz_kinetiq_01',
    supplierId: 'ernest',
    supplierName: 'Ernest Furnishings',
    requestId: 'req-1819',
    poNumber: 'PO-1819',
    status: 'SHIPPED',
    subtotal: 128400,
    taxAmount: 23112,
    freightAmount: 0,
    total: 128400,
    totalAmount: 151512,
    paymentTerms: '100% on delivery',
    deliveryTerms: 'Chennai Hub',
    deliveryAddress: 'Plot 42, Guindy Industrial Estate, Chennai',
    expectedDelivery: '2 Sep 2026',
    approvedBy: 'Sadwik Kumar',
    items: [
      {
        id: 'item-2',
        itemName: 'Industrial barcode roll labels',
        quantity: 15000,
        unitPrice: 8.56,
        taxRate: 18.0,
        totalAmount: 128400
      }
    ],
    createdAt: '2026-08-20T09:00:00Z'
  },
  {
    id: 'po-1812',
    businessId: 'biz_kinetiq_01',
    supplierId: 'sahara',
    supplierName: 'Sahara Workspace',
    requestId: 'req-1812',
    poNumber: 'PO-1812',
    status: 'ACKNOWLEDGED',
    subtotal: 88500,
    taxAmount: 15930,
    freightAmount: 0,
    total: 88500,
    totalAmount: 104430,
    paymentTerms: '30% advance',
    deliveryTerms: 'Bengaluru Facility',
    deliveryAddress: 'Outer Ring Road, Bengaluru',
    expectedDelivery: '6 Sep 2026',
    approvedBy: 'Sadwik Kumar',
    items: [
      {
        id: 'item-3',
        itemName: 'Conference room stools',
        quantity: 120,
        unitPrice: 737.5,
        taxRate: 18.0,
        totalAmount: 88500
      }
    ],
    createdAt: '2026-08-22T11:00:00Z'
  }
];

export const mockDocumentsStore: DocumentDTO[] = [
  {
    id: 'doc-1827',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1827',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    documentType: 'INVOICE',
    documentNumber: 'INV-1827',
    fileName: 'INV-1827-Cobalt.pdf',
    fileSizeBytes: 245000,
    mimeType: 'application/pdf',
    reconciliationStatus: 'MISMATCH',
    discrepancyNotes: 'Price mismatch detected: PO unit price is ₹740, Invoice unit price is ₹760 (₹10,000 variance).',
    extractions: [
      {
        id: 'ext-1',
        extractedPoNumber: 'PO-1827',
        extractedInvoiceNumber: 'INV-1827',
        extractedDate: '2026-09-01',
        extractedSupplier: 'Cobalt Office Systems',
        extractedQty: 500,
        extractedUnitPrice: 760,
        extractedTax: 18.0,
        extractedTotal: 448400,
        confidenceScore: 0.98,
        varianceDetected: true,
        varianceSummary: 'Unit price billed at ₹760 vs agreed ₹740'
      }
    ],
    uploadedAt: '2026-09-01T10:00:00Z'
  },
  {
    id: 'doc-po-1827',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1827',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    documentType: 'PURCHASE_ORDER',
    documentNumber: 'PO-1827',
    fileName: 'PO-1827-Approved.pdf',
    fileSizeBytes: 180000,
    mimeType: 'application/pdf',
    reconciliationStatus: 'VERIFIED',
    extractions: [
      {
        id: 'ext-2',
        extractedPoNumber: 'PO-1827',
        extractedSupplier: 'Cobalt Office Systems',
        extractedQty: 500,
        extractedUnitPrice: 740,
        extractedTax: 18.0,
        extractedTotal: 436600,
        confidenceScore: 0.99,
        varianceDetected: false
      }
    ],
    uploadedAt: '2026-08-28T10:05:00Z'
  },
  {
    id: 'doc-lr-8821',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1827',
    supplierId: 'cobalt',
    supplierName: 'Cobalt Office Systems',
    documentType: 'LORRY_RECEIPT',
    documentNumber: 'LR-8821',
    fileName: 'LR-2026-8821.pdf',
    fileSizeBytes: 120000,
    mimeType: 'application/pdf',
    reconciliationStatus: 'VERIFIED',
    extractions: [
      {
        id: 'ext-3',
        extractedPoNumber: 'PO-1827',
        extractedDate: '2026-08-30',
        extractedSupplier: 'VRL Logistics',
        confidenceScore: 0.96,
        varianceDetected: false
      }
    ],
    uploadedAt: '2026-08-30T14:30:00Z'
  }
];

export const mockShipmentsStore: Shipment[] = [
  {
    id: 'shp-1827',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1827',
    poNumber: 'PO-1827',
    supplierName: 'Cobalt Office Systems',
    trackingNumber: 'LR-2026-8821',
    carrierName: 'VRL Logistics',
    status: 'WAREHOUSE',
    risk: 'high',
    riskLevel: 'HIGH',
    expectedDelivery: '4 Sep 2026',
    estimatedDelayDays: 2.4,
    originLocation: 'Chennai Factory',
    destinationLocation: 'Guindy Warehouse, Chennai',
    currentLocation: 'Chennai warehouse',
    lastVerifiedEvent: 'Chennai warehouse arrival on 1 Sep, 14:32 IST',
    riskExplanation: 'Warehouse milestone missed. Supplier averages 1.2 days delay. No later carrier event confirmed.',
    events: [
      {
        id: 'evt-1',
        eventType: 'PO_CREATED',
        title: 'PO created',
        source: 'Procura Enterprise Core',
        isVerified: true,
        timestamp: '28 Aug 2026',
        details: 'PO-1827 generated and approved'
      },
      {
        id: 'evt-2',
        eventType: 'SUPPLIER_CONFIRMED',
        title: 'Supplier confirmed',
        source: 'Cobalt Office Systems',
        isVerified: true,
        timestamp: '29 Aug 2026',
        details: 'Order acknowledged for manufacturing and packing'
      },
      {
        id: 'evt-3',
        eventType: 'PICKED_UP',
        title: 'Picked up',
        source: 'LR verified · VRL Logistics',
        isVerified: true,
        timestamp: '30 Aug 2026',
        details: 'LR-2026-8821 issued'
      },
      {
        id: 'evt-4',
        eventType: 'WAREHOUSE_ARRIVAL',
        title: 'Chennai warehouse',
        location: 'Chennai Hub',
        source: 'LR + supplier event · Last verified',
        isVerified: true,
        timestamp: '1 Sep, 14:32 IST',
        details: 'Consignment arrived at regional sorting hub'
      },
      {
        id: 'evt-5',
        eventType: 'OUT_FOR_DELIVERY',
        title: 'Out for delivery',
        source: 'Logistics integration',
        isVerified: false,
        timestamp: 'Pending',
        details: 'No confirmed carrier dispatch event available'
      }
    ],
    recoveryOptions: [
      {
        id: 'rec-1',
        optionCode: 'WAIT',
        title: 'Option A: Wait for original shipment',
        description: 'No extra cost. Expected arrival with +2.4 days delay.',
        additionalCost: 0,
        delayAvoidedDays: 0,
        isRecommended: false,
        isApproved: false
      },
      {
        id: 'rec-2',
        optionCode: 'PARTIAL_REPLACEMENT',
        title: 'Option B: Expedite local warehouse buffer (100 units)',
        description: 'Priority courier dispatch for initial 100 units from local regional buffer.',
        additionalCost: 3500,
        delayAvoidedDays: 2.0,
        isRecommended: true,
        isApproved: false
      },
      {
        id: 'rec-3',
        optionCode: 'ALTERNATIVE_SUPPLIER',
        title: 'Option C: Alternative local supplier (Ernest Furnishings)',
        description: 'Immediate replacement dispatch from nearby Coimbatore facility.',
        additionalCost: 8000,
        delayAvoidedDays: 3.0,
        isRecommended: false,
        isApproved: false
      }
    ],
    createdAt: '2026-08-28T10:00:00Z'
  },
  {
    id: 'shp-1819',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1819',
    poNumber: 'PO-1819',
    supplierName: 'Ernest Furnishings',
    trackingNumber: 'LR-2026-9930',
    carrierName: 'Gati KWE',
    status: 'IN_TRANSIT',
    risk: 'low',
    riskLevel: 'LOW',
    expectedDelivery: '2 Sep 2026',
    estimatedDelayDays: 0.0,
    originLocation: 'Coimbatore Hub',
    destinationLocation: 'Chennai',
    currentLocation: 'In transit (Salem bypass)',
    lastVerifiedEvent: 'Carrier GPS milestone at 11:15 IST',
    events: [
      {
        id: 'evt-10',
        eventType: 'PICKED_UP',
        title: 'Picked up from Coimbatore factory',
        source: 'Gati API',
        isVerified: true,
        timestamp: '31 Aug 2026'
      },
      {
        id: 'evt-11',
        eventType: 'IN_TRANSIT',
        title: 'In transit',
        source: 'Gati Telemetry',
        isVerified: true,
        timestamp: '1 Sep 2026'
      }
    ],
    createdAt: '2026-08-31T08:00:00Z'
  },
  {
    id: 'shp-1812',
    businessId: 'biz_kinetiq_01',
    purchaseOrderId: 'po-1812',
    poNumber: 'PO-1812',
    supplierName: 'Sahara Workspace',
    status: 'PREPARED',
    risk: 'medium',
    riskLevel: 'MEDIUM',
    expectedDelivery: '6 Sep 2026',
    estimatedDelayDays: 1.0,
    originLocation: 'Bengaluru',
    destinationLocation: 'Bengaluru Facility',
    currentLocation: 'Prepared at supplier facility',
    lastVerifiedEvent: 'Supplier packaging notification',
    events: [
      {
        id: 'evt-20',
        eventType: 'PO_CREATED',
        title: 'PO Created',
        source: 'Procura',
        isVerified: true,
        timestamp: '22 Aug 2026'
      }
    ],
    createdAt: '2026-08-22T11:00:00Z'
  }
];

export const mockRiskEvents: RiskEventDTO[] = [
  {
    id: 'risk-1',
    shipmentId: 'shp-1827',
    title: 'PO-1827 Warehouse milestone missed',
    severity: 'HIGH',
    reason: 'Consignment remained in regional sorting hub 48h beyond expected dispatch window. Supplier averages 1.2 days delay.',
    impactDays: 2.4,
    costImpact: 0,
    isResolved: false,
    detectedAt: '2026-09-01T08:00:00Z'
  },
  {
    id: 'risk-2',
    shipmentId: 'shp-1812',
    title: 'PO-1812 Carrier pickup pending',
    severity: 'MEDIUM',
    reason: 'Goods prepared at Bengaluru supplier facility; carrier pickup unconfirmed.',
    impactDays: 1.0,
    costImpact: 0,
    isResolved: false,
    detectedAt: '2026-09-01T07:30:00Z'
  },
  {
    id: 'risk-3',
    shipmentId: 'shp-1819',
    title: 'PO-1819 Telemetry gap',
    severity: 'LOW',
    reason: 'Live tracking checkpoint update awaited from interstate highway corridor.',
    impactDays: 0.0,
    costImpact: 0,
    isResolved: true,
    detectedAt: '2026-08-31T18:00:00Z'
  }
];

export const mockNotificationsStore: NotificationDTO[] = [
  {
    id: 'notif-1',
    priority: 'CRITICAL',
    category: 'SHIPMENT',
    title: 'PO-1827 Delivery at Risk',
    message: 'Warehouse milestone delayed by 48h. Recovery options available for review.',
    linkHref: '/shipments/shp-1827',
    isRead: false,
    createdAt: '2026-09-01T09:30:00Z'
  },
  {
    id: 'notif-2',
    priority: 'HIGH',
    category: 'DOCUMENT',
    title: 'INV-1827 Price Variance Detected',
    message: 'Invoice billed at ₹760/unit vs approved PO-1827 at ₹740/unit (₹10,000 difference).',
    linkHref: '/documents/doc-1827',
    isRead: false,
    createdAt: '2026-09-01T09:20:00Z'
  },
  {
    id: 'notif-3',
    priority: 'MEDIUM',
    category: 'PROCUREMENT',
    title: 'Cobalt Negotiation Complete',
    message: 'Cobalt Office Systems confirmed ₹740/unit with freight included. Buyer approval required.',
    linkHref: '/negotiations/neg-cobalt',
    isRead: false,
    createdAt: '2026-09-01T09:12:00Z'
  },
  {
    id: 'notif-4',
    priority: 'LOW',
    category: 'SUPPLIER',
    title: 'ONDC Network Catalog Refreshed',
    message: '43 new commercial furniture suppliers indexed in southern region.',
    linkHref: '/suppliers',
    isRead: true,
    createdAt: '2026-09-01T08:00:00Z'
  }
];
